# Application name (optional)
spring.application.name=cstore-backend

# Fixed port – Angular will call this
server.port=8082

# MongoDB connection (adjust database name as needed)
spring.data.mongodb.uri=mongodb://localhost:27017/cstore

# If you want to disable security temporarily (to avoid login for testing)
# Uncomment the next line to bypass Spring Security auto-configuration:
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfigurationt.fetch-registry=trueclubhub_super_secret_key_must_be_at_least_32_chars!
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
eureka.client.enabled=false
spring.cloud.service-registry.auto-registration.enabled=false
groq.api.key=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