spring.application.name=Messaging
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=Messaging
# Optional if you have username/password
# spring.data.mongodb.username=myuser
# spring.data.mongodb.password=mypassword
server.port=8081


