spring.application.name=Messaging


spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Messaging
# Optional if you have username/password
# spring.data.mongodb.username=myuser
# spring.data.mongodb.password=mypassword
server.port=8081
# Gemini API Configuration
spring.ai.openai.api-key=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


spring.ai.openai.base-url=https://api.groq.com/openai

# Recommended fast & cheap model for trivia
spring.ai.openai.chat.options.model=llama-3.3-70b-versatile
# Alternatives: llama-3.1-8b-instant (faster, lighter)

# Optional settings
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=2000

#Allow large JSON bodies for base64 profile photos (up to 5MB)
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB
server.tomcat.max-http-form-post-size=25MB
server.tomcat.max-swallow-size=25MB

ollama:
url= http://localhost:11434
model= llama3.2

huggingface.api.token=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
spring.data.mongodb.gridfs.bucket=themes
# application.properties
spring.jackson.serialization.write-dates-as-timestamps=false