spring.application.name=AI-Service
server.port=8085

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/clubhub
spring.data.mongodb.database=clubhub

# Python AI Service URL
ai.service.python.url=http://localhost:5000

# CORS
spring.web.cors.allowed-origins=http://192.168.1.20:4200,http://localhost:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true
