spring.application.name=ClubHub

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=clubhub

# Server configuration
server.port=8083
server.address=0.0.0.0

# Logging
logging.level.org.springframework.data.mongodb=DEBUG
logging.level.com.clubhub=DEBUG

# CORS
spring.web.cors.allowed-origins=http://localhost:4200,http://192.168.1.20:4200
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*
spring.web.cors.allow-credentials=true

# Email
gmail.credentials.file=credentials.json
gmail.user.email=fandouli.mahou@gmail.com

# Frontend URL (IP WiFi)
app.frontend.url=http://192.168.1.20:4200

# CORS app
app.cors.allowed-origins=http://localhost:4200,http://192.168.1.20:4200