spring.application.name=ClubHub
spring.mongodb.uri=mongodb://localhost:27017/User
spring.mongodb.database=User
server.port=8081

# Logs utiles en dev
logging.level.org.springframework.data.mongodb=DEBUG


jwt.secret=clubhub_super_secret_key_must_be_at_least_32_chars!
jwt.expiration=86400000
# Allow large JSON bodies for base64 profile photos (up to 5MB)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.tomcat.max-http-form-post-size=5MB
server.tomcat.max-swallow-size=5MB


# Pour voir la cause exacte de l'erreur (stacktrace complète)
server.error.include-message=always
server.error.include-stacktrace=always

# Pour voir les erreurs Spring Data MongoDB (IMPORTANT)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.repository.query=DEBUG