spring.application.name=Virtual_Event_Management

# Connexion MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Virtual_Event

# Logs utiles en dev
logging.level.org.springframework.data.mongodb=DEBUG

server.port=8082

# Whisper local Python (votre serveur Flask)
whisper.api.url=http://localhost:9000/v1/audio/transcriptions

# HuggingFace (fallback gratuit)
huggingface.api.url=https://api-inference.huggingface.co/models/linagora/whisper-large-v3-tunisian
huggingface.api.token=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


# Langues supportées
whisper.supported.languages=ar,fr,en,es,de,it
whisper.default.language=ar